config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :submissions, only: [:index, :show]

  resources :tests do 
    member do 
      get :preview_test
    end
    collection do 
      post :collect_user_response
    end
  end

  get '/previous' => 'tests#previous_question'
  get '/next' => 'tests#next_question'
  get '/question' => 'tests#question_list'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def test
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="well">
    <p>Please read the instructions carefully before starting test:</p>
    <p><ul><li><strong>Once you click the 'Start test' button, you will have 20 minutes to answer the questions.</strong></li></p>
    <p><li><strong>Each question will have multiple choices.</strong></li></p>
    <p><li><strong>After the time for test expires or after you have attempted all questions, you will be logged out of the system.</strong></li></p>
    <p><li><strong>Please do not refresh the page while taking test, if you do refresh, you will not be rewarded any marks for the question. </strong></li></p>
    <p><li><strong>The test results will be announced offline by the System Administrator.</strong></li></ul></p>
  </div>
  <% if user_signed_in? %>
    <%= link_to "Start Test", tests_path, class: "btn-lg btn-success"%>
  <% else %>
    <%= link_to "Start Test", new_user_session_path, class: "btn-lg btn-success"%>
  <% end %>
</div>

<div class="container">
  <div class="row mt-5">
    <div class="col-md-12">
      <%= link_to "View All Submissions", submissions_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>